apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: twitter-scraper-secret
spec:
  encryptedData:
    TWITTER_AUTH_TOKEN: AgBL8e0AbrmZPWxE1dk7+MrLJZHhs0ZppUuBBbNeMbHhikJeiLan730OagYHhwFk1b0oeJ9sWLZucZJ/BqBCEfEkEyE03UHvWDF7hxEduVgxExFpDo5LkdZYA4ZnS53LUdni46HW3XSbE+8KrWmz6MPe88y6g3s5uWTklfURqepL01rR6VOterX8MqFVtg2g2EedI3fjZx+fB8OvaMFW9O6OACidvDmGZP0qKxS5JccMNE85Xj2mshhJcZpx7C1T4H+0nR3h2X7Ta5M08aWaRH/mhFc8/qIt79kuouXjBHperWG5Kqez+FkPwkkCT72QxB6i8Ea7S72Lt+6eO6j2dYccYcYWEQ68UzCFS9SWlat32fcvtw3ElJuLSbIqEbMnt6qaHp1Rzv9wJNLpq2VipZhdyniz0l4T9NoeI7hv6az67PBCa/yrbdrbtvvC+DdfaaxLjYOoU51w5e4hEXwfs/btfVHgcA1oGwcJCKPP32STht6SkBm9s34QRjAlXqB2V17oKx2wz2ZhIfMRclDbMgW62dgIYnOW2ijVJfk2yI8qKybMX9tM4gzf4XzbzfjG/dNT2h4igg6z2uxJ+WUcnuQY2zBf3pY5ZMeeoruMtUMQCi7dyhc1zOezYuatFUKrL3IyvInRiQWXMnHypwbfbUqdKMi/Xn7BOpRTrT5+kYd2+Cx3bsmlYQdLwN8ndSPlM8czIBT8dy779e+NoPVcJnfFuDFSHB0HsVma8YDBKWfbAEv54b7gJysV
  template:
    metadata:
      creationTimestamp: null
      name: twitter-scraper-secret
