apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: twitter-scraper-secret
spec:
  encryptedData:
    TWITTER_AUTH_TOKEN: AgCcArYTlkhDPm2EonJv4boQiwlaJUAHeglWCa3HmKV0jTtZ751jVvJeBTkM5NrsPT8FTJZth9o8oCeTU3/yOTrU7eO7xJF7jUH8XUshhqIe6fzmDfXOljvCIdeGo0aIjFLWyZLAzdcypT5E8Ts1neL9C0kJdLP5VlO7AMiypJsqYlq8LC2Nslfg9ICL64T+ijuB7+pHv8mViKg5u6CxhbD6WQLJO7UlvDVXaOLIN1qlMKXPbJyEc/RVqm2VcEWJX+VkiQpyajxkHq7FggyDg/uhODaS2GGnV2K7W5434ou69MT4CThyT2jacw2rOUuT5xRpzgAKCiSJAOGVDjF9FoRMh+gIDuccFKPVqash04TEQS2lW55zP+6/8fm4cmQu6e9uHxeBFZECE3w3xRPzBCrEMQvH3RS2wLtouTF+a/7Mk02nPZBWDKO4D5Eu0nKpwMDMPA5t4rzqPTZe87z8TqRhvYp9NLa0M6J2n4v0ckHilnc+YPHnb6RkRVVLNDpsIff+y+LShed71Mmg950sQOUBsHklC3UBagMXYRk+xCRMUDVj/NcgG/HgeF9hIL9470phYznvFLIPWrL47qqnR57CTvJRcPyD/VfmHrB83CgoLGUpw0S6McW70ZLw0biUQzKdxVwauNdyLXYZZjrAi6Wc4sZdA1Xg85FGCYWOqXKK1wAcdja9A9LgTF0spXhEXf8U7dakXgHTZLUY/lP0g4liGy+AjRdXNNNu6nMYLdkkC3tOaUwHrdGL
  template:
    metadata:
      creationTimestamp: null
      name: twitter-scraper-secret
