apiVersion: v1
kind: Service
metadata:
  name: twitter-scraper-service
spec:
  type: ClusterIP
  selector:
    app: twitter-scraper
  ports:
    - name: rest
      port: 5000
      targetPort: rest
      protocol: TCP
